{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2503691-cae8-4519-ba74-198db99efe08",
   "metadata": {},
   "outputs": [],
   "source": [
    "from fastapi import FastAPI\n",
    "from pydantic import BaseModel\n",
    "import pickle\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.preprocessing import PolynomialFeatures\n",
    "\n",
    "# ── App ────────────────────────────────────────────────────────────────────────\n",
    "app = FastAPI(title=\"Bucknell Lending Club — Loan Prediction API\")\n",
    "\n",
    "# ── Load models ────────────────────────────────────────────────────────────────\n",
    "with open(\"classifier.pkl\",  \"rb\") as f: clf        = pickle.load(f)\n",
    "with open(\"scaler_clf.pkl\",  \"rb\") as f: scaler_clf = pickle.load(f)\n",
    "with open(\"regressor.pkl\",   \"rb\") as f: reg        = pickle.load(f)\n",
    "with open(\"scaler_reg.pkl\",  \"rb\") as f: scaler_reg = pickle.load(f)\n",
    "\n",
    "CLF_NUM_COLS = ['loan_amnt','annual_inc','dti','delinq_2yrs','open_acc',\n",
    "                'pub_rec','revol_bal','revol_util','term_num','fico_score',\n",
    "                'grade_numeric','risk_loan_amnt_tradeoff']\n",
    "CLF_ALL_COLS = list(clf.feature_names_in_)\n",
    "REG_ALL_COLS = list(reg.feature_names_in_)\n",
    "\n",
    "# ── Input schema ───────────────────────────────────────────────────────────────\n",
    "class LoanApplication(BaseModel):\n",
    "    loan_amnt:           float\n",
    "    term_num:            int           # 36 or 60\n",
    "    int_rate:            float\n",
    "    grade:               str           # A-G\n",
    "    emp_length:          str           # e.g. \"10+ years\"\n",
    "    home_ownership:      str           # MORTGAGE, RENT, OWN, OTHER\n",
    "    annual_inc:          float\n",
    "    verification_status: str           # Verified, Source Verified, Not Verified\n",
    "    purpose:             str           # debt_consolidation, credit_card, etc.\n",
    "    dti:                 float\n",
    "    delinq_2yrs:         int\n",
    "    open_acc:            int\n",
    "    pub_rec:             int\n",
    "    fico_range_high:     float\n",
    "    fico_range_low:      float\n",
    "    revol_bal:           float\n",
    "    revol_util:          float\n",
    "\n",
    "# ── Preprocessing ──────────────────────────────────────────────────────────────\n",
    "def preprocess(inp: dict) -> pd.DataFrame:\n",
    "    df = pd.DataFrame([inp])\n",
    "\n",
    "    df[\"fico_score\"]             = (df[\"fico_range_high\"] + df[\"fico_range_low\"]) / 2\n",
    "    df                           = df.drop(columns=[\"fico_range_high\",\"fico_range_low\"])\n",
    "    df[\"grade_numeric\"]          = df[\"grade\"].map({\"A\":1,\"B\":2,\"C\":3,\"D\":4,\"E\":5,\"F\":6,\"G\":7})\n",
    "    df[\"risk_loan_amnt_tradeoff\"] = df[\"loan_amnt\"] * df[\"grade_numeric\"]\n",
    "    df[\"annual_inc\"]             = np.log1p(df[\"annual_inc\"])\n",
    "    df[\"revol_util\"]             = df[\"revol_util\"].clip(upper=100)\n",
    "    df[\"home_ownership\"]         = df[\"home_ownership\"].apply(\n",
    "        lambda x: x if x in [\"MORTGAGE\",\"RENT\"] else \"OTHER\")\n",
    "    df[\"purpose\"]                = df[\"purpose\"].apply(\n",
    "        lambda x: x if x in [\"debt_consolidation\",\"credit_card\"] else \"OTHER\")\n",
    "    df = df.drop(columns=[\"grade\",\"int_rate\",\"installment\",\"funded_amnt\",\n",
    "                           \"id\",\"issue_d\",\"earliest_cr_line\",\"term\"], errors=\"ignore\")\n",
    "    df = pd.get_dummies(df, columns=[\"emp_length\",\"home_ownership\",\n",
    "                                      \"verification_status\",\"purpose\"], drop_first=True)\n",
    "    return df\n",
    "\n",
    "def build_clf_input(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    df = df.copy()\n",
    "    num = [c for c in CLF_NUM_COLS if c in df.columns]\n",
    "    df[num] = scaler_clf.transform(df[num])\n",
    "    for col in CLF_ALL_COLS:\n",
    "        if col not in df.columns: df[col] = 0\n",
    "    return df[CLF_ALL_COLS]\n",
    "\n",
    "def build_reg_input(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    df = df.copy()\n",
    "    for col in CLF_ALL_COLS:\n",
    "        if col not in df.columns: df[col] = 0\n",
    "    df_28   = df[CLF_ALL_COLS]\n",
    "    poly    = PolynomialFeatures(degree=2, include_bias=False)\n",
    "    arr     = poly.fit_transform(df_28)\n",
    "    df_poly = pd.DataFrame(arr, columns=poly.get_feature_names_out(CLF_ALL_COLS))\n",
    "    for col in REG_ALL_COLS:\n",
    "        if col not in df_poly.columns: df_poly[col] = 0\n",
    "    df_poly = df_poly[REG_ALL_COLS]\n",
    "    df_poly[REG_ALL_COLS] = scaler_reg.transform(df_poly[REG_ALL_COLS])\n",
    "    return df_poly\n",
    "\n",
    "# ── Endpoints ──────────────────────────────────────────────────────────────────\n",
    "@app.get(\"/\")\n",
    "def home():\n",
    "    return {\"message\": \"Bucknell Lending Club Prediction API is running 🦬\"}\n",
    "\n",
    "@app.post(\"/predict\")\n",
    "def predict(application: LoanApplication):\n",
    "    inp     = application.dict()\n",
    "    df_base = preprocess(inp)\n",
    "\n",
    "    # Classifier\n",
    "    X_clf           = build_clf_input(df_base)\n",
    "    proba           = clf.predict_proba(X_clf)[0]\n",
    "    prob_fully_paid = round(float(proba[1]), 4)\n",
    "    prob_default    = round(float(proba[0]), 4)\n",
    "\n",
    "    # Regressor\n",
    "    X_reg       = build_reg_input(df_base)\n",
    "    pred_return = round(float(reg.predict(X_reg)[0]), 4)\n",
    "\n",
    "    # Recommendation\n",
    "    if prob_fully_paid >= 0.75 and pred_return >= 0:\n",
    "        recommendation = \"APPROVE\"\n",
    "    elif prob_fully_paid >= 0.55 and pred_return >= -2:\n",
    "        recommendation = \"MANUAL REVIEW\"\n",
    "    else:\n",
    "        recommendation = \"DECLINE\"\n",
    "\n",
    "    return {\n",
    "        \"prob_fully_paid\":   prob_fully_paid,\n",
    "        \"prob_default\":      prob_default,\n",
    "        \"predicted_return\":  pred_return,\n",
    "        \"recommendation\":    recommendation\n",
    "    }"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
